### ISSUE TITLE
Help GoUniverse

### ISSUE THREAD

**Issue by Lecale** [jkk/shinkgs#215] opened 2019-09-23 19:17 UTC
Please, whatever it took to fix ShinKGS, can you share it with Ilya.

https://github.com/IlyaKirillov/GoUniverse/issues/66

**Comment by steppefox** [comment] 2020-09-10 16:19
Seems the issue is resolved in GoUniverse, @leeschumacher can you close it?

**Closed** 2020-09-12 07:28 UTC
